image: python:alpine

stages:
  - preparing_runner
  - test
  - build
  - delivery
  
preparing_runner:
  stage: preparing_runner
  script:
    - apk add --no-cache \
        gcc \
        libressl-dev \
        musl-dev \
        libffi-dev && \
        pip install --no-cache-dir poetry
    
    #- apk del \
    #    gcc \
    #    libressl-dev \
    #    musl-dev \
    #    libffi-dev

test:
  stage: test
  script:
    - poetry run pytest

build:
  stage: build  
  script:
    - poetry build