image: python:3.8

stages:
  - test
  - lint
  - types
  - deploy

before_script:
  - pip install poetry
  - poetry config virtualenvs.create false
  - poetry install

Unit Tests:
  stage: test
  script:
    - poetry run pytest