image: python:alpine

stages:
  - test
  - build
  - delivery
  
before_script:
  - apk add curl #\
    #make \
    #openssh \
    #vim \
    #py-pip \
  - curl -sSL https://raw.githubusercontent.com/python-poetry/poetry/master/get-poetry.py | python -
  - poetry --version

test:
  stage: test
  script:
    - poetry run pytest

build:
  stage: build  
  script:
    - poetry build