image: python:alpine

stages:
    - test
    - build
    - delivery
  

run:
  script:
    - apk add curl #\
    #make \
    #openssh \
    #vim \
    #py-pip \
    
    - curl -sSL https://raw.githubusercontent.com/python-poetry/poetry/master/get-poetry.py | python -