image: python:alpine

stages:
  - preparing_runner
  - test
  - build
  - delivery
  
preparing_runner:
  stage: preparing_runner
  script:
    - apk add curl #\
      #make \
      #openssh \
      #vim \
      #py-pip \
    - curl -sSL https://raw.githubusercontent.com/python-poetry/poetry/master/get-poetry.py | python -
    - reboot
    - poetry --version

test:
  stage: test
  script:
    - poetry run pytest

build:
  stage: build  
  script:
    - poetry build